// This script plots the hit.n distribution from qsim rootfiles
// Takes qsim rootfiles which is generated by hitting detector by physics event generator

#include <string>
#include <iostream>
#include <map>
#include "TROOT.h"
#include "TChain.h"
#include "TStyle.h"
#include "TGaxis.h"
#include "TFile.h"
#include "TH1I.h"
#include "TTree.h"
#include "TCanvas.h"
#include "TPaveStats.h"
#include "TSystem.h"
#include "TLatex.h"

using namespace std;

void plot_hitn_evgen(){
    //gROOT->Reset();
    gStyle->SetOptStat("neMR");
    //gStyle->SetTitleYOffset(1.3);
    //gStyle->SetPadGridX(1);
    //gStyle->SetPadGridY(1);
    //TGaxis::SetMaxDigits(3);
    
    string config = "qsim_20";
    string generator[] = {"moller", "elastic", "inelastic"};
    string sector[] = {"open", "closed", "trans"};
    string particle[] = {"electron", "gamma"};
    string geometry = "smFullscaleQsim";
    int color[3][2] = {{kBlack, kRed}, {kGreen+2, kBlue}, {kMagenta, kCyan+2}};
    int nGen = 3;
    int nSector = 3;
    int nParticle = 2;

    int hist_xmin = 0;
    int hist_xmax = 500;
    int nbins = 100;

    //TString inFileDir = Form("/volatile/halla/moller12gev/sudip/qsim_rootfiles/%s/",config.c_str());
    //TString inFileDir = Form("~/programs/qsim/qsim-showermax/rootfiles/%s/", config.c_str());
    TString inFileDir = Form("/run/user/1000/gvfs/sftp:host=sudips-mbp.local/Users/sudip/test/qsim_rootfiles/%s/", config.c_str());
    TString inRootFileName[nSector][nParticle];

    TH1D *h_hitn[nSector][nParticle];
    TCanvas *c[nGen];

    for (int iGen=0; iGen<nGen; iGen++){
        c[iGen] = new TCanvas(Form("c_%s", generator[iGen].c_str()), "Photon distribution");
        for (int iSector=0; iSector<nSector; iSector++){
            for (int iParticle=0; iParticle<nParticle; iParticle++){
                inRootFileName[iSector][iParticle] = Form("qsim_out_%s_%s_%s.root", generator[iGen].c_str(), sector[iSector].c_str(), particle[iParticle].c_str());
                TString inRootFile = inFileDir + inRootFileName[iSector][iParticle];
                
                TFile *inFile = new TFile(inRootFile, "READ");
                TTree *T = (TTree*)inFile->Get("T");
                
                T->Draw(Form("hit.n>>h_hitn_%s_%s", sector[iSector].c_str(), particle[iParticle].c_str()), "", "goff");
                //h_hitn[iSector][iParticle] = new TH1D(Form("h_hitn_%s_%s", sector[iSector].c_str(), particle[iParticle].c_str()), 
                        //Form("PE hits distribution of %s, %s sector, %s;PE per event; Counts/bin", geometry.c_str(), sector[iSector].c_str(), particle[iParticle].c_str()),
                        //nbins, hist_xmin, hist_xmax);

                h_hitn[iSector][iParticle] = (TH1D*)gDirectory->FindObject(Form("h_hitn_%s_%s", sector[iSector].c_str(), particle[iParticle].c_str()));

            }
        }

        for (int iSector=0; iSector<nSector; iSector++){
            for (int iParticle=0; iParticle<nParticle; iParticle++){
                h_hitn[iSector][iParticle]->SetTitle(Form("PE Response of %s generator; PE/event; Counts/bin", generator[iGen].c_str()));
                h_hitn[iSector][iParticle]->SetMarkerStyle(20);
                h_hitn[iSector][iParticle]->SetMarkerSize(1.5);
                h_hitn[iSector][iParticle]->SetLineColor(color[iSector][iParticle]);
                h_hitn[iSector][iParticle]->SetAxisRange(0, 1000, "Y");
                h_hitn[iSector][iParticle]->Draw("hist sames");
            }
        }

        TPaveStats* stat[nSector][nParticle];
        TLatex * res = new TLatex();
        res->SetTextFont(42);
        res->SetTextSize(0.03);

        c[iGen]->Update();
        float widthStat = 0.25; //width of a stat box
        float heightStat = 0.20;
        float gap = 0.05;
        int nColStat = nSector;   //number of columns of the stat boxes
        
        for (int iSector=0; iSector<nSector; iSector++){
            for (int iParticle=0; iParticle<nParticle; iParticle++){
                //h_hitn[iSector][iParticle]->SetStats("neMR");
                stat[iSector][iParticle] = (TPaveStats*)h_hitn[iSector][iParticle]->FindObject("stats");
                //stat[iSector][iParticle] = (TPaveStats*)c1->GetPrimitive("stats");
                stat[iSector][iParticle]->SetTextColor(color[iSector][iParticle]);
                stat[iSector][iParticle]->SetX1NDC(0.9-(iSector+1)*widthStat);
                stat[iSector][iParticle]->SetX2NDC(0.9-(iSector)*widthStat);
                stat[iSector][iParticle]->SetY1NDC(0.9-(iParticle)*heightStat);
                stat[iSector][iParticle]->SetY2NDC(0.9-(iParticle+1)*(heightStat)+gap);

                //stat[iSector][iParticle]->Print();
                stat[iSector][iParticle]->Draw();

                //Resolution print in the pad
                res->DrawLatexNDC(0.9-(iSector+1)*widthStat+0.01, 0.9-(iParticle+1)*heightStat+0.015, Form("RMS/Mean = %0.1f", h_hitn[iSector][iParticle]->GetStdDev()/h_hitn[iSector][iParticle]->GetMean()));
            }
        }
        c[iGen]->SaveAs(Form("./plots/%s/hitDistn_%s.pdf",config.c_str(), generator[iGen].c_str()));
    }

/*
    double rms = h_hitn->GetRMS();
    double mean = h_hitn->GetMean();
    double res = rms/mean;
    TString resText = Form("#frac{RMS}{Mean} = %.1f", rms/mean);

    TLatex latex;
    latex.SetNDC(1);
    latex.SetTextSize(0.03);
    latex.SetTextColor(kRed);
    latex.DrawLatex(0.7, 0.6, resText);

    //gSystem->Exec(Form("mkdir -p plots/%s/",config.c_str()));
    //c1->SaveAs(Form("./plots/%s/%s_%s.pdf",config.c_str(), geometry.c_str(),particle.c_str()));
*/
}
